//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModuleStatu()
        {
            this.StatusItems = new HashSet<StatusItem>();
        }
    
        public int ModuleStatusId { get; set; }
        public string CustomHtml { get; set; }
        public int MinutesUntilWarning { get; set; }
        public int MinutesUntilError { get; set; }
        public string MachineName { get; set; }
        public string StatusLine { get; set; }
        public int RefModuleTypeId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string LogText { get; set; }
        public bool IsLogHtml { get; set; }
        public bool IsForcedSuccess { get; set; }
        public bool IsInProgress { get; set; }
        public string InProgressUserid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatusItem> StatusItems { get; set; }
        public virtual RefModuleType RefModuleType { get; set; }
    }
}
