//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusItem
    {
        public int StatusItemId { get; set; }
        public string AppId { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public string ItemStatus { get; set; }
        public Nullable<int> ModuleStatusId { get; set; }
        public bool Display { get; set; }
        public bool InProgress { get; set; }
        public string InProgressUserid { get; set; }
    
        public virtual ModuleStatu ModuleStatu { get; set; }
    }
}
